config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all

  end

  def new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
      @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>edit</title>
    <meta charset="UTF-8">
  </head>

  <body>

    <div>
      <%= flash[:notice] %>
    </div>
    
        <h1>Editing Book</h1>
        
    <% if @book.errors.any? %>
      <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <%= form_with model: @book, url:book_path(@book.id), method: :patch do |f| %>
      <div>
          <h4>Title</h4>
          <%= f.text_field :title %>
      </div>
      
      <div>
          <h4>Body</h4>
          <%= f.text_area :body %>
      </div>
          <%= f.submit 'Update Book' %>
    <% end %>


      <table>
    <tr>
        <td>
          <%= link_to "Show", book_path(@book.id) %>
        </td>
        <td>|</td>
        <td>
          <%= link_to "Back", books_path %>
        </td>
    </tr>
  </table>


  </body>

</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>index</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>

  <div>
    <%= flash[:notice] %>
  </div>

    <h1>Books</h1>
    <p></p>

      <table>
        <thead>
            <tr>
              <th>Title</th>
              <th>Body</th>
              <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.body %></td>
              <td><%= link_to "Show", book_path(book.id) %></td>
              <td><%= link_to "Edit", edit_book_path(book.id) %></td>
              <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    <h1>New book</h1>
       <%= form_with(model:@book, local: true) do |form| %>
          <% if @book.errors.any? %>
          <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
       <% end %>
    <%= form_with model: @book do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Body</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
    <% end %>
  </body>

</html>

app/views/books/new.html.erb
<h1>新規投稿</h1>

app/views/books/show.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title>show</title>
    <meta charset="UTF-8">
  </head>

  <body>

    <div>
　    <%= flash[:notice] %>
    </div>

  <table>
    <tr>
      <td>
        <strong>Title:</strong>
      </td>
      <td>
        <p><%= @book.title %></p>
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <td>
        <strong>Body:</strong>
      </td>
      <td>
        <p><%= @book.body %></p>
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <td>
          <%= link_to "Edit", edit_book_path(@book.id) %>
      </td>
        <td>|</td>
      <td>
        <%= link_to "Back", books_path %>
      </td>
    </tr>
  </table>
  </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>

 <head>
  <title>Bookers</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
 </head>

 <body>

   <h1>
     ようこそ
   <strong>Bookers</strong>
     へ！
   </h1>

   <p>
    <strong>Bookers</strong>
    では、さまざまな書籍に関するあなたの意見や
   </p>
   <p></p>
   <p>印象を共有し交換することができます</p>

   <p>
     <a href="/books">start</a>
   </p>
 </body>



</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>